markdown: kramdown

plugins:
 - jekyll-multiple-languages-plugin
 - jekyll-liquify

languages: ["en", "es"]

exclude_from_localizations: ["js", "img", "css", "fonts", "CNAME","scripts", "TRANSLATIONS.md"]

coin: "Masari"