title: "Cams site yo"
description:
markdown: kramdown
url: ""
baseurl: ""

plugins:
 - jekyll-multiple-languages-plugin

languages: ["en", "es"]

exclude_from_localizations: ["js", "img", "css", "fonts", "CNAME"]